### ISSUE TITLE
Static links generated by Go are not copy-paste friendly

### ISSUE THREAD

**Issue by pierreprinetti** [shiftstack/gazelle#4]
The link to the build log used to be a fomula where the build ID is passed by reference. That makes copy-paste easy in Spreadsheets.

Now that the links are being assembled in Go, you can't drag the cell corner all the way up to get links to the build logs: all the links will point to the same page.

**Comment by mandre** [comment]
Is there still a need for this now that the gazelle takes care of inserting the jobs reports in the spreadsheet? I do not see a use case for dragging formulas across cells anymore now that it's fully automated.

**Comment by pierreprinetti** [comment]
Right! Closing. :tada:
